name = "panasms-oauth-gateway"
main = "src/index.js"
compatibility_date = "2026-09-01"
workers_dev = true

# Created with: wrangler kv namespace create STATE
[[kv_namespaces]]
binding = "STATE"
id = "a69ad1b2086845a3a0bde644c52009fb"
